# sonar.projectKey=ai-coding-assistant
# sonar.projectName=AI Coding Assistant
# sonar.projectVersion=1.0

# sonar.sources=app

# sonar.sourceEncoding=UTF-8
# sonar.python.version=3.11

# sonar.exclusions=**/.venv/**,**/venv/**,**/__pycache__/**,**/node_modules/**,**/dist/**,**/build/**,**/demo_projects/**

# sonar.projectKey=ai-coding-assistant
# sonar.projectName=AI Coding Assistant
# sonar.projectVersion=1.0

# sonar.sources=app
# sonar.sourceEncoding=UTF-8
# sonar.python.version=3.11

# sonar.exclusions=**/.venv/**,**/venv/**,**/__pycache__/**,**/node_modules/**,**/dist/**,**/build/**,**/demo_projects/**,app/static/**,**/*.js,**/*.css,**/*.html

sonar.projectKey=ai-coding-demo-projects
sonar.projectName=AI Coding Demo Projects
sonar.projectVersion=1.0

sonar.sources=demo_projects
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11

sonar.exclusions=**/.venv/**,**/venv/**,**/__pycache__/**,**/node_modules/**,**/dist/**,**/build/**,**/*.js,**/*.css,**/*.html

sonar.coverage.exclusions=**
