apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-coding-assistant
  namespace: ai-coding
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: ai-coding-assistant
  template:
    metadata:
      labels:
        app: ai-coding-assistant
    spec:
      containers:
        - name: ai-coding-assistant
          image: raedbari/ai-coding-assistant:8691c780d349a84982ec0b49b8b358ff55907229
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: SONAR_HOST_URL
              value: "http://10.0.0.136:9000"

            - name: SONAR_PROJECT_KEY
              value: "ai-coding-demo-projects"

            - name: SONAR_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sonar-credentials
                  key: SONAR_TOKEN

