apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-coding-assistant
  namespace: ai-coding
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: ai-coding-assistant
  template:
    metadata:
      labels:
        app: ai-coding-assistant
    spec:
      containers:
        - name: ai-coding-assistant
          image: raedbari/ai-coding-assistant:bc1ebacef8f64ba2b670d7ebb4b9f34501340fab
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: SONAR_HOST_URL
              value: "http://10.0.0.136:9000"

            - name: SONAR_PROJECT_KEY
              value: "ai-coding-demo-projects"

            - name: SONAR_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sonar-credentials
                  key: SONAR_TOKEN

            - name: LLM_PROVIDER
              value: "deepseek"

            - name: LLM_BASE_URL
              value: "https://api.deepseek.com"

            - name: LLM_MODEL
              value: "deepseek-v4-flash"

            - name: LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm-credentials
                  key: LLM_API_KEY

            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: GITHUB_TOKEN

            - name: GITHUB_REPO_URL
              value: "https://github.com/raedbari/Ai-Agent-Coding-Assisstant.git"

            - name: GITHUB_BRANCH
              value: "main"

            - name: GIT_AUTHOR_NAME
              value: "AI Coding Assistant"

            - name: GIT_AUTHOR_EMAIL
              value: "ai-coding-assistant@users.noreply.github.com"

            - name: LANGGRAPH_CHECKPOINT_DATABASE_URL
              valueFrom:
                secretKeyRef:
                   name: langgraph-checkpointer
                   key: LANGGRAPH_CHECKPOINT_DATABASE_URL


                   